In [10]:
import pandas as pd

# Step 1: Load Pre-study.csv
per_trial = pd.read_csv('/Users/Patron/Desktop/project/data/per-trial.csv')

In [11]:
per_trial.isna().sum()

participant_id                      0
input_type                          0
model_order                         0
diagnosis_type                      0
shown_confidence_A                  0
shown_confidence_B                  0
trust_rating_A                      0
trust_rating_B                      0
first_response_confidence_rating    0
final_confidence_rating             0
preferred_model                     0
response_rating                     0
trust_reasoning_text                0
dtype: int64

In [12]:
per_trial['input_type_encoded'] = per_trial['input_type'].map({
    'text': 0,
    'image': 1
})

In [19]:
per_trial['model_order_encoded'] = per_trial['model_order'].map({
    'A, B': 0,
    'B, A': 1
})

In [20]:
per_trial['diagnosis_type_encoded'] = per_trial['diagnosis_type'].map({
    'consistent': 0,
    'conflicting': 1,
    'partially_consistent': 1
})

In [27]:
per_trial['preferred_model'] = per_trial['preferred_model'].str.strip().str.capitalize()

per_trial['preferred_model_encoded'] = per_trial['preferred_model'].map({
    'A': 0,
    'B': 1,
    'Both': 2
})

In [28]:
import re

def extract_confidence(value):
    if pd.isna(value):
        return 0
    value = value.strip()
    if value.lower() == 'no':
        return 0
    match = re.search(r'\((\d+)\)', value)
    if match:
        return int(match.group(1))
    else:
        return 0  # default if something weird happens

# Apply the function to both columns
per_trial['shown_confidence_A_numeric'] = per_trial['shown_confidence_A'].apply(extract_confidence)
per_trial['shown_confidence_B_numeric'] = per_trial['shown_confidence_B'].apply(extract_confidence)

In [29]:
per_trial.drop(columns=['input_type','model_order','diagnosis_type','preferred_model', 'trust_reasoning_text','shown_confidence_A','shown_confidence_B'])

,participant_id,trust_rating_A,trust_rating_B,first_response_confidence_rating,final_confidence_rating,response_rating,input_type_encoded,model_order_encoded,diagnosis_type_encoded,preferred_model_encoded,shown_confidence_A_numeric,shown_confidence_B_numeric
0,aish,5,2,2,4,5,1,0,1,2,5,4
1,akan,5,5,5,5,5,0,1,0,2,5,3
2,akas,4,4,4,4,4,0,0,0,1,0,0
3,anan,4,3,4,5,5,1,0,1,2,2,5
4,arju,5,4,5,5,5,1,0,1,0,0,0
5,jyot,5,3,3,3,4,0,1,0,0,0,0
6,kath,5,5,2,2,5,0,1,0,2,3,1
7,kesa,2,2,4,5,3,0,1,0,0,4,1
8,madh,3,5,4,3,5,0,0,1,1,0,0
9,mano,4,2,5,4,4,1,0,1,0,0,0
10,moni,4,5,4,5,5,0,1,0,1,5,4
11,navi,5,2,5,5,5,0,0,1,0,5,3
12,nira,4,3,3,3,4,0,1,0,0,5,1
13,prak,3,4,4,3,4,0,0,1,1,5,2
14,ramm,4,3,4,4,4,0,0,0,0,3,2
15,sah,4,2,4,4,4,0,1,1,1,0,1
16,sasi,5,2,2,2,5,1,0,1,1,0,5
17,shar,5,1,4,5,4,1,0,1,0,0,0
18,soni,3,2,2,2,4,0,0,0,1,1,4
19,srir,3,5,5,4,4,0,1,0,1,3,5
20,swet,4,3,3,4,4,0,0,0,0,3,2

In [30]:
per_trial.to_csv("/Users/Patron/Desktop/project/data/per_trial_cleaned.csv")